### ISSUE TITLE
Call to undefined function Spatie\SslCertificate\idn_to_ascii()

### ISSUE THREAD

**Issue by monkeyphysics** [spatie/ssl-certificate#68]
With a completely fresh install, I get this error.

Steps to reproduce:
```
$ mkdir test
$ cd test
$ composer require spatie/ssl-certificate
$ echo "<?php include 'vendor/autoload.php'; use Spatie\SslCertificate\SslCertificate; SslCertificate::createForHostName('spatie.be');" > test.php
$ php test.php
```

Result:
```
~$ mkdir test ; cd test
~/test$ composer require spatie/ssl-certificate
Using version ^1.12 for spatie/ssl-certificate
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing spatie/macroable (1.0.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing symfony/translation (v4.0.9): Loading from cache
  - Installing nesbot/carbon (1.27.0): Loading from cache
  - Installing spatie/ssl-certificate (1.12.3): Loading from cache
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
Writing lock file
Generating autoload files
~/test$ echo "<?php include 'vendor/autoload.php'; use Spatie\SslCertificate\SslCertificate; SslCertificate::createForHostName('spatie.be');" > test.php
~/test$ php test.php

Fatal error: Uncaught Error: Call to undefined function Spatie\SslCertificate\idn_to_ascii() in ~/test/vendor/spatie/ssl-certificate/src/Url.php:21
Stack trace:
#0 ~/test/vendor/spatie/ssl-certificate/src/Downloader.php(123): Spatie\SslCertificate\Url->__construct('https://spatie....')
#1 ~/test/vendor/spatie/ssl-certificate/src/Downloader.php(134): Spatie\SslCertificate\Downloader->forHost('spatie.be')
#2 ~/test/vendor/spatie/ssl-certificate/src/SslCertificate.php(25): Spatie\SslCertificate\Downloader::downloadCertificateFromUrl('spatie.be', 30)
#3 test/test.php(1): Spatie\SslCertificate\SslCertificate::createForHostName('spatie.be')
#4 {main}
  thrown in ~/test/vendor/spatie/ssl-certificate/src/Url.php on line 21
~/test$
```

PHP version
```
~/test$ php -v
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by monkeyphysics** [comment]
Turns out `idn_to_ascii()` is a required global function, available in the php `intl` extension.

**Comment by krisnaw** [comment]
How to solved this issue?
